### PR TITLE
Feature re designdaily

### PR DESCRIPTION
**Pull request by CS6**
Re-design daily card view & add svg
image

### CODE REVIEW

**Comment by shc261392** [comment]
@CS6 
1. The bottommost part looks like being cropped on Nokia 6.1 and it becomes a serious issue if there are many symptoms to present (the user can't see the third line and so on)

2. According to the discussion with UI, the dismiss behavior should be "If the user clicked on anywhere else on the page, the prompt will be dismissed". The current behavior is that the user must click on the arrow button again to dismiss it.

**Comment by CS6** [comment]
@shc261392  fixed!!🚀
image

**Comment by shc261392** [comment]
@CS6 I've fixed this


>According to the discussion with UI, the dismiss behavior should be "If the user clicked on anywhere else on the page, the prompt will be dismissed". The current behavior is that the user must click on the arrow button again to dismiss it.

Please review the fix. If it's ok this PR could be merged

**Comment by CS6** [comment]
[ Known issues ]
ios 似乎要觸發其他 click 才能作用？（偶而）

**Pull request merged**
